import 'package:flutter/material.dart';
  final ThemeData myTheme = ThemeData(
    primarySwatch: Colors.orange,
    brightness: Brightness.light,
    primaryColor: Color( 0xffff9800 ),
    primaryColorBrightness: Brightness.light,
    primaryColorLight: Color( 0xffffe0b2 ),
    primaryColorDark: Color( 0xfff57c00 ),
    accentColor: Color( 0xffff9800 ),
    accentColorBrightness: Brightness.light,
    canvasColor: Color( 0xfffafafa ),
    scaffoldBackgroundColor: Color( 0xfffafafa ),
    bottomAppBarColor: Color( 0xffffffff ),
    cardColor: Color( 0xffffffff ),
    dividerColor: Color( 0x1f000000 ),
    highlightColor: Color( 0x66bcbcbc ),
    splashColor: Color( 0x66c8c8c8 ),
    selectedRowColor: Color( 0xfff5f5f5 ),
    unselectedWidgetColor: Color( 0x8a000000 ),
    disabledColor: Color( 0x61000000 ),
    buttonColor: Color( 0xffe0e0e0 ),
    toggleableActiveColor: Color( 0xfffb8c00 ),
    secondaryHeaderColor: Color( 0xfffff3e0 ),
 
    backgroundColor: Color( 0xffffcc80 ),
    dialogBackgroundColor: Color( 0xffffffff ),
    indicatorColor: Color( 0xffff9800 ),
    hintColor: Color( 0x8a000000 ),
    errorColor: Color( 0xffd32f2f ),
 );